package com.indhawk.billable.billablews.requests;

import com.indhawk.billable.models.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class InvoiceConfigRequest {
    private String invoiceNumber;
    private String poNumber;
    private InvoiceCategory invoiceCategory;
    private Customer customer;
    private Address shipTo;
    private LocalDateTime dueDate;
    private BillableItems billableItems;
    private Disclaimer disclaimer;
    private Discount discount;
    private AdditionalDetail additionalDetail;
    // Tag customerOrgId generated by Billable system. So that customer can see sent invoices on portal after login.
    private long customerOrgId;

}
